/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * HEXA-R Verification Report Modal
 * Whitish-black EDA sign-off report with bold black typography,
 * floating card presentation, and export options.
 */

import React, { useState } from 'react';
import { VerificationReport } from '../../types';
import { 
  FileText, 
  X, 
  Download, 
  Copy, 
  Check, 
  CheckCircle2, 
  XCircle,
  Cpu
} from 'lucide-react';

interface VerificationReportModalProps {
  isOpen: boolean;
  report: VerificationReport | null;
  onClose: () => void;
}

export const VerificationReportModal: React.FC<VerificationReportModalProps> = ({
  isOpen,
  report,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !report) return null;

  const isPass = report.overallStatus === 'PASS';

  const exportAsMarkdown = () => {
    const md = `# RTL VERIFICATION REPORT
Generated by HEXA-R (Private On-Device AI Copilot for RTL Engineering)
Timestamp: ${report.timestamp}
Project: ${report.projectName}
Overall Sign-off Status: ${report.overallStatus}

## 1. Static Analysis
- Errors: ${report.staticAnalysis.errorsCount}
- Warnings: ${report.staticAnalysis.warningsCount}

## 2. Compilation
- Status: ${report.compilation.status}
- Compiler: ${report.compilation.compiler}

## 3. Simulation
- Status: ${report.simulation.status}
- Simulator: ${report.simulation.simulator}
- Duration: ${report.simulation.durationMs}ms

## 4. Tests
- Total: ${report.tests.total}
- Passed: ${report.tests.passed}
- Failed: ${report.tests.failed}

## 5. Assertions (SVA)
- Total: ${report.assertions.total}
- Passed: ${report.assertions.passed}
- Failed: ${report.assertions.failed}

## 6. Synthesizability
- Status: ${report.synthesizability.status}
- Score: ${report.synthesizability.score}%
- Inferred Latches: ${report.synthesizability.inferredLatches}

## 7. AI Architectural Review (Snapdragon Hexagon NPU)
${report.aiReview.summary}

Improvements:
${report.aiReview.improvements.map(i => `- ${i}`).join('\n')}
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.projectName.toLowerCase().replace(/\s+/g, '_')}_verification_report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(JSON.stringify(report, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-md p-4 animate-in fade-in duration-150">
      <div className="bg-white border-2 border-black rounded-2xl shadow-2xl w-full max-w-3xl max-h-[85vh] flex flex-col overflow-hidden text-black font-mono text-xs animate-modal-float">
        
        {/* Header (Crisp White with Bold Black Text) */}
        <div className="h-14 px-5 bg-white border-b-2 border-black flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <span className="p-2 rounded-xl bg-black text-white">
              <FileText className="w-5 h-5 text-white" />
            </span>
            <div>
              <div className="flex items-center space-x-2">
                <h3 className="font-black text-sm text-black uppercase tracking-tight">RTL VERIFICATION SIGN-OFF REPORT</h3>
                <span
                  className={`text-[11px] font-black px-2.5 py-0.5 rounded-full border-2 ${
                    isPass
                      ? 'bg-emerald-100 text-emerald-950 border-emerald-800'
                      : 'bg-rose-100 text-rose-950 border-rose-800'
                  }`}
                >
                  {report.overallStatus}
                </span>
              </div>
              <p className="text-[11px] text-black font-bold">
                Project: {report.projectName} • Generated: {report.timestamp}
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="p-1.5 rounded-lg bg-white hover:bg-slate-100 text-black border-2 border-black cursor-pointer transition-colors"
              title="Copy JSON"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            </button>
            <button
              onClick={exportAsMarkdown}
              className="px-3 py-1.5 rounded-lg bg-black hover:bg-slate-800 text-white font-black text-xs transition-colors flex items-center gap-1.5 cursor-pointer shadow-xs"
              title="Export as Markdown document"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .MD</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-black hover:bg-slate-100 rounded-lg border-2 border-black cursor-pointer transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4 bg-white">
          
          {/* Sign-off Banner in Bold Black Words */}
          <div
            className={`p-4 rounded-xl border-2 flex items-center justify-between ${
              isPass
                ? 'bg-emerald-50 border-emerald-800 text-emerald-950'
                : 'bg-rose-50 border-rose-800 text-rose-950'
            }`}
          >
            <div className="flex items-center space-x-3">
              {isPass ? (
                <CheckCircle2 className="w-8 h-8 text-emerald-700 flex-shrink-0" />
              ) : (
                <XCircle className="w-8 h-8 text-rose-700 flex-shrink-0" />
              )}
              <div>
                <h4 className="font-black text-sm uppercase tracking-wide">
                  {isPass ? 'TAPEOUT / SYNTHESIS SIGN-OFF READY' : 'SIGNOFF BLOCKED: VERIFICATION FAILURES'}
                </h4>
                <p className="text-xs font-bold mt-0.5">
                  {isPass
                    ? 'All 48 testbench cycles, formal SVA assertions, and synthesizability checks passed cleanly.'
                    : 'Timing mismatch detected during frame reception. Review diff and apply correction.'}
                </p>
              </div>
            </div>
          </div>

          {/* Metric Summary Grid (Floating Cards with Bold Typography) */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="floating-card p-3 rounded-xl bg-white border-2 border-black">
              <span className="text-[10px] text-black font-black uppercase tracking-wider block">
                STATIC ANALYSIS
              </span>
              <div className="mt-1 text-base font-black text-black">
                {report.staticAnalysis.errorsCount} err / {report.staticAnalysis.warningsCount} warn
              </div>
              <span className="text-[10px] text-black font-bold">Rule Engine v2.4</span>
            </div>

            <div className="floating-card p-3 rounded-xl bg-white border-2 border-black">
              <span className="text-[10px] text-black font-black uppercase tracking-wider block">
                TESTBENCH PASS RATE
              </span>
              <div
                className={`mt-1 text-base font-black ${
                  report.tests.failed > 0 ? 'text-rose-700' : 'text-emerald-700'
                }`}
              >
                {report.tests.passed}/{report.tests.total} ({Math.round((report.tests.passed / report.tests.total) * 100)}%)
              </div>
              <span className="text-[10px] text-black font-bold">Cycle-accurate simulation</span>
            </div>

            <div className="floating-card p-3 rounded-xl bg-white border-2 border-black">
              <span className="text-[10px] text-black font-black uppercase tracking-wider block">
                SVA ASSERTIONS
              </span>
              <div
                className={`mt-1 text-base font-black ${
                  report.assertions.failed > 0 ? 'text-amber-700' : 'text-emerald-700'
                }`}
              >
                {report.assertions.passed}/{report.assertions.total} PASS
              </div>
              <span className="text-[10px] text-black font-bold">SystemVerilog Assertions</span>
            </div>

            <div className="floating-card p-3 rounded-xl bg-white border-2 border-black">
              <span className="text-[10px] text-black font-black uppercase tracking-wider block">
                SYNTHESIZABILITY
              </span>
              <div className="mt-1 text-base font-black text-black">
                {report.synthesizability.score}%
              </div>
              <span className="text-[10px] text-black font-bold">0 Latches Inferred</span>
            </div>
          </div>

          {/* AI Architectural Summary (Snapdragon NPU) */}
          <div className="p-4 rounded-xl bg-slate-50 border-2 border-black space-y-2">
            <div className="flex items-center space-x-2 text-black font-black text-xs uppercase tracking-wide">
              <Cpu className="w-4 h-4 text-black" />
              <span>Snapdragon Hexagon NPU Architectural Assessment</span>
            </div>
            <p className="text-xs text-black font-bold leading-relaxed">
              {report.aiReview.summary}
            </p>

            <div className="pt-2">
              <span className="text-[11px] font-black text-black uppercase tracking-wider block mb-1">
                Proposed Microarchitecture Improvements:
              </span>
              <ul className="space-y-1">
                {report.aiReview.improvements.map((imp, idx) => (
                  <li key={idx} className="text-xs text-black font-bold flex items-start space-x-1.5">
                    <span className="text-black font-black">•</span>
                    <span>{imp}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="h-12 px-5 bg-white border-t-2 border-black flex items-center justify-between text-xs text-black font-bold">
          <span className="font-black">HEXA-R Private On-Device RTL Assistant • No Cloud Telemetry</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-white hover:bg-slate-100 text-black border-2 border-black font-black cursor-pointer transition-colors"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
};
